mqtt:
  enabled: false

model:
  path: /config/model_cache/yolov8n.onnx
  model_type: yolo-generic
  width: 640
  height: 640
  input_tensor: nchw
  input_pixel_format: rgb
  input_dtype: float
  labelmap:
    0: person

detectors:
  nvidia:
    type: onnx
    device: auto

# -----------------------------------------------------------
# STREAMS
# -----------------------------------------------------------
go2rtc:
  api:
    listen: ":1984"
  streams:

    # --- CAM 13 ---
    cam_13_h265:
      - "rtsp://192.168.0.13:554/user=admin_password=tlJwpbo6_channel=0_stream=0&onvif=0.sdp?real_stream&transport=tcp#audio=aac"
    cam_13_sub:
      - "rtsp://192.168.0.13:554/user=admin_password=tlJwpbo6_channel=0_stream=1&onvif=0.sdp?real_stream&transport=tcp#video=h264#audio=aac"
    cam_13:
      # Transcode to H.264 using NVIDIA hardware acceleration
      - "ffmpeg:cam_13_h265#video=h264#hardware=cuda"

    # --- CAM 21 ---
    cam_21_h265:
      - "rtsp://192.168.0.21:554/user=admin_password=tlJwpbo6_channel=0_stream=0&onvif=0.sdp?real_stream&transport=tcp#audio=aac"
    cam_21_sub:
      - "rtsp://192.168.0.21:554/user=admin_password=tlJwpbo6_channel=0_stream=1&onvif=0.sdp?real_stream&transport=tcp#video=h264#audio=aac"
    cam_21:
      - "ffmpeg:cam_21_h265#video=h264#hardware=cuda"

    # --- CAM 19 ---
    cam_19_h265:
      - "rtsp://192.168.0.19:554/user=admin_password=tlJwpbo6_channel=0_stream=0&onvif=0.sdp?real_stream&transport=tcp#audio=aac"
    cam_19_sub:
      - "rtsp://192.168.0.19:554/user=admin_password=tlJwpbo6_channel=0_stream=1&onvif=0.sdp?real_stream&transport=tcp#video=h264#audio=aac"
    cam_19:
      - "ffmpeg:cam_19_h265#video=h264#hardware=cuda"

cameras:

  cam_13:
    ffmpeg:
      inputs:
      # CHANGED: Record from the transcoded 'cam_13' stream
      - path: rtsp://127.0.0.1:8554/cam_13?video=copy
        roles: [record]
      - path: rtsp://127.0.0.1:8554/cam_13_sub?video=copy
        roles: [detect]
    detect:
      enabled: true
      width: 640
      height: 360
      fps: 5

  cam_21:
    ffmpeg:
      inputs:
      # CHANGED: Record from the transcoded 'cam_21' stream
      - path: rtsp://127.0.0.1:8554/cam_21?video=copy
        roles: [record]
      - path: rtsp://127.0.0.1:8554/cam_21_sub?video=copy
        roles: [detect]
    detect:
      enabled: true
      width: 640
      height: 360
      fps: 5

  cam_19:
    ffmpeg:
      inputs:
      # CHANGED: Record from the transcoded 'cam_19' stream
      - path: rtsp://127.0.0.1:8554/cam_19?video=copy
        roles: [record]
      - path: rtsp://127.0.0.1:8554/cam_19_sub?video=copy
        roles: [detect]
    detect:
      enabled: true
      width: 640
      height: 360
      fps: 5

record:
  enabled: true
  retain:
    days: 3
    mode: motion

snapshots:
  enabled: true

detect:
  enabled: true