mqtt:
  enabled: false

# -----------------------------------------------------------
# GLOBAL MODEL CONFIGURATION
# -----------------------------------------------------------
model:
  path: /config/model_cache/yolov8n.onnx
  model_type: yolo-generic
  width: 640
  height: 640
  input_tensor: nchw
  input_pixel_format: rgb
  input_dtype: float
  labelmap:
    0: person

# -----------------------------------------------------------
# DETECTOR HARDWARE
# -----------------------------------------------------------
detectors:
  nvidia:
    type: onnx
    device: auto

# -----------------------------------------------------------
# STREAMS (TCP Added for Stability)
# -----------------------------------------------------------
go2rtc:
  api:
    listen: ":1984"
  streams:
    sala: 
      - rtsp://192.168.2.5:554/user=sala_password=w25JVsMW_channel=0_stream=0&onvif=0.sdp?real_stream&transport=tcp
      - "ffmpeg:sala#audio=aac"
    edicula: "rtsp://192.168.2.4:554/user=admin_password=tlJwpbo6_channel=0_stream=0&onvif=0.sdp?real_stream&transport=tcp"
    garagem: "rtsp://192.168.2.64:554/user=garagem_password=w25JVsMW_channel=0_stream=0&onvif=0.sdp?real_stream&transport=tcp"

cameras:
  sala:
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/sala
          input_args: preset-rtsp-restream
          roles:
            - record
            - detect
    detect:
      width: 1920
      height: 1080
      fps: 5
      enabled: true

  edicula:
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/edicula?video=copy
          input_args: preset-rtsp-restream
          roles:
            - record
            - detect
    detect:
      width: 1920
      height: 1080
      fps: 5
      enabled: true

  garagem:
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/garagem?video=copy
          input_args: preset-rtsp-restream
          roles:
            - record
            - detect
    detect:
      width: 1920
      height: 1080
      fps: 5
      enabled: true

record:
  enabled: true
  retain:
    days: 3
    mode: motion

snapshots:
  enabled: true

detect:
  enabled: true
version: 0.16-0
