version: '3.9'
services:
  frigate:
    container_name: frigate
    privileged: true
    restart: unless-stopped
    # optimize for NVIDIA GPUs
    image: ghcr.io/blakeblackshear/frigate:stable-tensorrt
    shm_size: "1gb"
    network_mode: host
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu, compute, video]
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ./config.yml:/config/config.yml:ro      # <--- CHANGED
      - ./storage:/media/frigate                  # <--- CHANGED
      - ./model_cache:/config/model_cache         # <--- CHANGED
      - type: tmpfs
        target: /tmp/cache
        tmpfs:
          size: 1000000000
