version: '3.9'
services:
  frigate:
    container_name: frigate
    privileged: true
    restart: unless-stopped
    # optimize for NVIDIA GPUs
    image: ghcr.io/blakeblackshear/frigate:stable-tensorrt
    shm_size: "1gb"
    networks:
      - proxy-net
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu, compute, video]
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ./:/config             # Mapeia sua pasta local .config/frigate para o container
      - ./storage:/media/frigate
networks:
  proxy-net:
    external: true
